# Generated by Django 2.2.7 on 2019-11-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_details',
            field=models.TextField(verbose_name='Blog Details'),
        ),
    ]
