# Generated by Django 2.2.7 on 2019-11-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_auto_20191107_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/user.jpg', upload_to='images', verbose_name='Profile Pic'),
        ),
    ]
