# Generated by Django 2.2.7 on 2019-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_details',
            field=models.TextField(default=0, max_length=1000, verbose_name='Course Details'),
            preserve_default=False,
        ),
    ]
